services:
  view:
    image: elkinms/accounting:0.1.0
    container_name: accounting
    ports:
      - "80:80"
    depends_on:
      - forum-service
  forum-service:
    image: elkinms/forum-service:0.1.0
    container_name: forum
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb+srv://elkinms:elkinms4603842@cluster0.0r6g3kj.mongodb.net/java59?retryWrites=true&w=majority&appName=Cluster0
      - PORT=8080
      - DB_NAME=java59
